<a href="https://colab.research.google.com/github/ishitha1611/Training/blob/main/TrainingDay32%2633.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')

In [ ]:
titanic = pd.read_csv(r"/content/Titanic.csv")

In [ ]:
titanic.head()

  Class Gender    Age Survived
0   3rd   Male  Child       No
1   3rd   Male  Child       No
2   3rd   Male  Child       No
3   3rd   Male  Child       No
4   3rd   Male  Child       No

In [ ]:
titanic['Class'].unique()

array(['3rd', '1st', '2nd', 'Crew'], dtype=object)

In [ ]:
titanic['Class'].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [ ]:
titanic['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
titanic['Gender'].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [ ]:
titanic['Age'].unique()

array(['Child', 'Adult'], dtype=object)

In [ ]:
titanic['Age'].value_counts()

Age
Adult    2092
Child     109
Name: count, dtype: int64

In [ ]:
titanic['Survived'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
titanic['Survived'].value_counts()

Survived
No     1490
Yes     711
Name: count, dtype: int64

In [ ]:
df = pd.get_dummies(titanic,dtype='int')
df.head()

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,0,0,1,0,0,1,0,1,1,0
1,0,0,1,0,0,1,0,1,1,0
2,0,0,1,0,0,1,0,1,1,0
3,0,0,1,0,0,1,0,1,1,0
4,0,0,1,0,0,1,0,1,1,0

In [ ]:
frequent_itemsets = apriori(df,min_support=0.1,use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Age_Adult, Class_1st)
10  0.118582                             (Age_Adult, Class_2nd)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Survived_No, Class_3rd)
14  0.391640                          (Class_Crew, Gender_Male)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Survived_No, Class_Crew)
17  0.193094                         (Gender_Female, Age_Adult)
18  0.156293                      (Gender_Female, Survived_Yes)
19  0.757383                           (Age_Adult, Gender_Male)
20  0.619718                         (Survived_No, Gender_Male)
21  0.166742                        (Survived_Yes, Gender_Male)
22  0.653339                           (Survived_No, Age_Adult)
23  0.297138                          (Age_Adult, Survived_Yes)
24  0.209905                (Class_3rd, Age_Adult, Gender_Male)
25  0.191731              (Survived_No, Class_3rd, Gender_Male)
26  0.216265                (Survived_No, Class_3rd, Age_Adult)
27  0.391640               (Class_Crew, Age_Adult, Gender_Male)
28  0.304407             (Survived_No, Class_Crew, Gender_Male)
29  0.305770               (Survived_No, Class_Crew, Age_Adult)
30  0.143571           (Gender_Female, Age_Adult, Survived_Yes)
31  0.603816              (Survived_No, Age_Adult, Gender_Male)
32  0.153567             (Age_Adult, Survived_Yes, Gender_Male)
33  0.175829   (Survived_No, Class_3rd, Age_Adult, Gender_Male)
34  0.304407  (Survived_No, Class_Crew, Age_Adult, Gender_Male)

In [32]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,1.0,0.004587,1.005694,0.639010,0.152050,0.005661,0.567012
1,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,1.0,0.004587,2.682493,0.037128,0.152050,0.627212,0.567012
2,(Survived_No),(Class_3rd),0.676965,0.320763,0.239891,0.354362,1.104747,1.0,0.022745,1.052040,0.293515,0.316547,0.049466,0.551119
3,(Class_3rd),(Survived_No),0.320763,0.676965,0.239891,0.747875,1.104747,1.0,0.022745,1.281251,0.139592,0.316547,0.219513,0.551119
4,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,"(Age_Adult, Gender_Male)","(Survived_No, Class_Crew)",0.757383,0.305770,0.304407,0.401920,1.314450,1.0,0.072822,1.160764,0.986022,0.401198,0.138498,0.698731
70,(Survived_No),"(Class_Crew, Age_Adult, Gender_Male)",0.676965,0.391640,0.304407,0.449664,1.148157,1.0,0.039280,1.105434,0.399458,0.398335,0.095378,0.613463
71,(Class_Crew),"(Survived_No, Age_Adult, Gender_Male)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600
72,(Age_Adult),"(Survived_No, Class_Crew, Gender_Male)",0.950477,0.304407,0.304407,0.320268,1.052103,1.0,0.015075,1.023334,1.000000,0.320268,0.022802,0.660134
73,(Gender_Male),"(Survived_No, Class_Crew, Age_Adult)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301

In [33]:
rules[rules['support']>0.5]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
12,(Age_Adult),(Gender_Male),0.950477,0.786461,0.757383,0.796845,1.013204,1.0,0.009870,1.051116,0.263149,0.773191,0.048630,0.879936
13,(Gender_Male),(Age_Adult),0.786461,0.950477,0.757383,0.963027,1.013204,1.0,0.009870,1.339441,0.061028,0.773191,0.253420,0.879936
14,(Survived_No),(Gender_Male),0.676965,0.786461,0.619718,0.915436,1.163995,1.0,0.087312,2.525187,0.436144,0.734518,0.603990,0.851710
15,(Gender_Male),(Survived_No),0.786461,0.676965,0.619718,0.787984,1.163995,1.0,0.087312,1.523634,0.659783,0.734518,0.343674,0.851710
16,(Survived_No),(Age_Adult),0.676965,0.950477,0.653339,0.965101,1.015386,1.0,0.009900,1.419023,0.046906,0.670709,0.295290,0.826241
17,(Age_Adult),(Survived_No),0.950477,0.676965,0.653339,0.687380,1.015386,1.0,0.009900,1.033317,0.305968,0.670709,0.032243,0.826241
48,"(Survived_No, Age_Adult)",(Gender_Male),0.653339,0.786461,0.603816,0.924200,1.175139,1.0,0.089991,2.817152,0.429921,0.722283,0.645032,0.845982
49,"(Survived_No, Gender_Male)",(Age_Adult),0.619718,0.950477,0.603816,0.974340,1.025106,1.0,0.014788,1.929980,0.064404,0.624824,0.481860,0.804809
50,"(Age_Adult, Gender_Male)",(Survived_No),0.757383,0.676965,0.603816,0.797241,1.177669,1.0,0.091095,1.593193,0.621823,0.727024,0.372330,0.844593
51,(Survived_No),"(Age_Adult, Gender_Male)",0.676965,0.757383,0.603816,0.891946,1.177669,1.0,0.091095,2.245337,0.467023,0.727024,0.554633,0.844593
52,(Age_Adult),"(Survived_No, Gender_Male)",0.950477,0.619718,0.603816,0.635277,1.025106,1.0,0.014788,1.042660,0.494550,0.624824,0.040914,0.804809
53,(Gender_Male),"(Survived_No, Age_Adult)",0.786461,0.653339,0.603816,0.767764,1.175139,1.0,0.089991,1.492710,0.697935,0.722283,0.330078,0.845982